export const env = {
  WHATSAPP_NUMBER_PRIMARY: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER_PRIMARY ?? "59176498138",
  WHATSAPP_NUMBER_SECONDARY: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER_SECONDARY ?? "",
  CURRENCY_SYMBOL: process.env.NEXT_PUBLIC_CURRENCY_SYMBOL ?? "Bs",
};
